### ISSUE TITLE
about test_otb_attack.py

### ISSUE THREAD

**Issue by laisimiao** [joshuajss/RTAA#1]
Hi,@joshuajss, Thank you for your open codes.But I have a confusion about following :
https://github.com/joshuajss/RTAA/blob/e9fed9d6c8626a1646258dfc81edfee5d71f109d/DaSiamRPN/code/test_otb_attack.py#L108 
Why tracker just track the videos that v_id > 27?

**Comment by joshuajss** [comment]
There is a bug. We will fix it. Thx.

The v_id depends on which videos you wanna attack in the dataset.
